### ISSUE TITLE
Gradle 3.2 - Task.leftShift(Closure) method has been deprecated

### ISSUE THREAD

**Issue by jaredsburrows** [kageiit/gradle-lintrules-plugin#3]
`The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.`

https://github.com/kageiit/gradle-lintrules-plugin/blob/master/lintrules/src/main/groovy/com/kageiit/LintRulesPlugin.groovy#L54

Just re-write it to use `doLast` instead.

**Comment by jaredsburrows** [comment]
@kageiit Can you quickly fix this and make a release or do you want a pull request?

**Comment by kageiit** [comment]
Let me make the change. I was on vacation last week :)

**Comment by kageiit** [comment]
1.1.3 is released with the fix

https://plugins.gradle.org/plugin/com.kageiit.lintrules

Thanks!

**Comment by jaredsburrows** [comment]
@kageiit Thanks!
