### ISSUE TITLE
Request to add support for non-project lint rules

### ISSUE THREAD

**Issue by jaredsburrows** [kageiit/gradle-lintrules-plugin#4]
For example, I cannot add this to my project https://bitbucket.org/littlerobots/rxlint.

    lintRules "nl.littlerobots.rxlint:rxlint:1.0"

**Comment by kageiit** [comment]
One way you can do this currently is to have your lint project depend on the external jar and modify your lint registry to also include the checks from the consumed jar.

This is a limitation of the android build system. It only allows one lint.jar per aar and only one lint registry class in the manifest

**Comment by jaredsburrows** [comment]
@kageiit Yeah. This is a limitation and thanks, I can use that work around. This would require the lint detector to have their `Issue` be public so I can add it to my `Registry`.

**Comment by kageiit** [comment]
In your case, you can just fork that library since it's opensource as well. So it should not be a problem.

Closing this issue as there is not much the plugin can do

**Comment by jaredsburrows** [comment]
Sounds good. Thanks!

**Comment by jaredsburrows** [comment]
@kageiit Since all Registries extend `IssueRegistry`, you can just call `getIssues` to add your existing `Issues`. Thanks for the tip!

I added the gradle dependency in the `compile` configuration of the lint project module using `@jar` as the qualifier to ignore the transitive dependencies and only bring in the `Detector` and `Registry`. Then when adding to your existing `IssueRegistry`, simply call: `issues.addAll(new SomeIssueRegistry().getIssues());`
